name: Incrementar versión y publicar

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'

    - name: Instalar dependencias
      run: npm install

    - name: Github
      run: |
        git config user.name MisaelMa
        git config user.email amisael.amir.misael@gmail.com

    - name: Publish
      run: npm run semantic-release
      env: 
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        GH_TOKEN: ${{ secrets.GIT_TOKEN }}
